# =====================================================================
# SIGAP — Konfigurasi Mosquitto MQTT broker
# =====================================================================

# Listener MQTT standar (edge / DeepStream / simulator / backend)
listener 1883
protocol mqtt

# Listener WebSocket (opsional: klien browser bisa subscribe langsung)
listener 9001
protocol websockets

# Tahap awal: izinkan koneksi anonim di jaringan internal Docker.
# PRODUKSI: set allow_anonymous false dan pakai password_file / TLS.
allow_anonymous true

# Persistensi pesan tertahan & sesi
persistence true
persistence_location /mosquitto/data/

# Logging
log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true
